=== sahmedASC/Nothing-of-note/UIUC Data Curation/Assignment 2/Part 1/step2_selected_document_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name = "accountStatement">
    <xs:complexType>
        <xs:sequence>
            <xs:element name = "summaryHeader" minOccurs = "1" maxOccurs = "1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="accountSummary" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                                <xs:attribute name="summary" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="Checking Summary"/>
                                            <xs:enumeration value="Savings Summary"/>     
                                            <xs:enumeration value="Certificate of Deposit Summary"/> 
                                            <xs:enumeration value="Money Market Account Summary"/>
                                            <xs:enumeration value="Individual Retirement Accounts  Summary"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name = "accountTypeDesc" minOccurs="1" maxOccurs="1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name = "desc" minOccurs = "1" maxOccurs ="1" type= "xs:string"/>
                                </xs:sequence>
                            <xs:attribute name = "accountType" use = "optional"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name ="balanceBreakdown" minOccurs="1" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="balanceBreakdownHeader" maxOccurs= "1" type="xs:string"/>
                        <xs:element name = "beginningBalance" minOccurs="1" maxOccurs = "1" type="xs:string"/>
                        <xs:element name = "beginningBalanceAmount" minOccurs="1" maxOccurs = "1" type="xs:decimal"/>
                        <xs:element name = "deposits" maxOccurs = "1" type="xs:string"/>
                        <xs:element name = "depositAmount" maxOccurs = "1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="deposit" minOccurs = "1" maxOccurs ="1">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                            <xs:minInclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>   
                        </xs:element>
                        <xs:element name = "physicalWithdrawals" maxOccurs = "1" type="xs:string"/>
                        <xs:element name = "physicalWithdrawalsAmount" maxOccurs = "1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="withdrawal" minOccurs = "1" maxOccurs ="1">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                            <xs:maxInclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name = "electronicWithdrawals" maxOccurs = "1" type="xs:string"/>
                        <xs:element name = "electronicWithdrawalsAmount" maxOccurs = "1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="withdrawal" minOccurs = "1" maxOccurs ="1">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:decimal">
                                            <xs:maxInclusive value="0"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>                            
                        </xs:element>
                        <xs:element name = "endingBalance" minOccurs="1" maxOccurs = "1" type="xs:string"/>
                        <xs:element name = "endingBalanceAmount" minOccurs="1" maxOccurs = "1" type="xs:decimal"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name = "noteToMember" minOccurs = "1" maxOccurs ="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "note" minOccurs = "1" maxOccurs = "1" type="xs:string"/>
                    </xs:sequence>
                    <xs:attribute name="noteType" use="required"/>
                </xs:complexType>
            </xs:element>

            <xs:element name = "transactions" minOccurs = "1" maxOccurs = "1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name = "headersList" maxOccurs= "unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name = "tableHeader" maxOccurs="unbounded" type="xs:string"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name = "transBeginningBalance" minOccurs="1" maxOccurs = "1" type="xs:string"/>
                        <xs:element name = "transBeginningBalanceAmount" minOccurs="1" maxOccurs = "1" type="xs:string"/>

                        <xs:element name = "transactionTable" minOccurs="1" maxOccurs = "1">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name = "row" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name = "date" minOccurs="1" maxOccurs = "1" type = "xs:string"/>
                                                <xs:element name = "description" minOccurs="1" maxOccurs = "1" type = "xs:string"/>
                                                <xs:element name = "amount" minOccurs="1" maxOccurs = "1" type = "xs:string"/>
                                                <xs:element name = "balance" minOccurs="1" maxOccurs = "1" type = "xs:string"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name = "transEndingBalance" minOccurs="1" maxOccurs = "1" type = "xs:string"/>
                        <xs:element name = "transEndingBalanceAmount" minOccurs="1" maxOccurs = "1" type = "xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="currency" use="required"/>
        <xs:attribute name="language" use="optional" default = "EN"/>
    </xs:complexType>
</xs:element>
</xs:schema>

=== sahmedASC/Nothing-of-note/UIUC Data Curation/Assignment 2/Part 1/step4_marked_up_document.xml
<?xml version="1.0" encoding="utf-8"?>
<accountStatement xsi:noNamespaceSchemaLocation="step2_selected_document_xsd.xsd" currency="USD" language="EN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<summaryHeader>
		<accountSummary summary="Checking Summary" />
		<accountTypeDesc accountType="College">
			<desc>Chase College Checking</desc>
		</accountTypeDesc>
	</summaryHeader>
	<balanceBreakdown>
		<balanceBreakdownHeader>Amount</balanceBreakdownHeader>
		<beginningBalance>Beginning Balance</beginningBalance>
		<beginningBalanceAmount>5755.47</beginningBalanceAmount>
		<deposits>Deposits and Additions</deposits>
		<depositAmount>
			<deposit>7227.52</deposit>
		</depositAmount>
		<physicalWithdrawals>Physical Withdrawals</physicalWithdrawals>
		<physicalWithdrawalsAmount>
			<withdrawal>0.00</withdrawal>
		</physicalWithdrawalsAmount>
		<electronicWithdrawals>Electronic Withdrawals</electronicWithdrawals>
		<electronicWithdrawalsAmount>
			<withdrawal>-3737.98</withdrawal>
		</electronicWithdrawalsAmount>
		<endingBalance>Ending Balance</endingBalance>
		<endingBalanceAmount>9244.01</endingBalanceAmount>
	</balanceBreakdown>
	<noteToMember noteType="waiver">
		<note>Your Chase College Checking Monthly Service Fee was waived because during the statement you had an electronic deposit made
            into this account, such as a payment from payroll providers or government benefit providers, by using (i) the ACH network,
            (ii) the Real Time Payment network, or (iii) third party services that facilitate payments to your debit card using the Visa
            Mastercard network.
        </note>
	</noteToMember>
	<transactions>
		<headersList>
			<tableHeader>Date</tableHeader>
			<tableHeader>Description</tableHeader>
			<tableHeader>Amount</tableHeader>
            <tableHeader>Balance</tableHeader>
		</headersList>
		<transBeginningBalance>Beginnning Balance</transBeginningBalance>
		<transBeginningBalanceAmount>$5,755.47</transBeginningBalanceAmount>
		<transactionTable>
			<row>
				<date>08/15</date>
				<description>Bogus Corp Dir Dep</description>
				<amount>2,409.17</amount>
				<balance>8,164.64</balance>
			</row>
            <row>
				<date>08/16</date>
				<description>15th Street Housing Rent Payment</description>
				<amount>$2,640.00</amount>
				<balance>5,524.64</balance>
			</row>
		</transactionTable>
		<transEndingBalance>Ending Balance</transEndingBalance>
		<transEndingBalanceAmount>$5,524.64</transEndingBalanceAmount>
	</transactions>
</accountStatement>
